- name: Enable bastion specific repos (redhat)
  command: "subscription-manager repos --enable={{item}}"
  retries: 5
  delay: 5
  with_items: "{{repos_bastion}}"
  when: openshift_deployment == "openshift-enterprise"

- name: Enable bastion specific repos (centos)
  yum:
    name: "{{origin_repos_bastion}}"
    state: latest
  retries: 5
  delay: 5
  when: openshift_deployment == "origin"

- name: Ensure that required packages are installed on bastion
  yum:
    name: "{{packages}}"
    state: latest
  retries: 5
  delay: 5

- name: Perform yum update
  yum:
    name=*
    state=latest

- name: Install required openstack packages for bastion (redhat)
  yum:
    name: "{{packages_bastion_openstack}}"
    state: installed
    disablerepo: rhel-7-fast-datapath-rpms
    disablerepo: rhel-7-server-ose-{{ openshift_version }}-rpms
  when: openshift_deployment == "openshift-enterprise"

- name: Install required openstack packages for bastion (centos)
  yum:
    name: "{{packages_bastion_openstack}}"
    state: installed
  when: openshift_deployment == "origin"

- name: Install required installer packages for bastion (redhat)
  yum:
    name: "{{packages_bastion_openshift}}"
    state: installed
    disablerepo: rhel-7-server-openstack-{{ openstack_version }}-tools-rpms
  when: openshift_deployment == "openshift-enterprise"

- name: Install required installer packages for bastion (centos)
  yum:
    name: "{{packages_bastion_origin}}"
    state: installed
  when: openshift_deployment == "origin"

- name: Disable epel repository (centos)
  yum_repository:
    name: epel
    baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    description: "EPEL"
    enabled: no
  when: openshift_deployment == "origin"

- name: Clone OKD repository
  git:
    repo: 'https://github.com/openshift/openshift-ansible'
    dest: /home/{{ ssh_user }}/openshift-ansible
    version: release-{{ openshift_version }}
  when: openshift_deployment == "origin"

- name: Copy OpenStack ssh key to bastion
  copy:
    src: "{{ ssh_key_path }}"
    dest: /home/{{ ssh_user }}/admin.pem
    mode: 0400
    owner: "{{ ssh_user }}"

- name: Copy playbooks to bastion
  copy:
    src: "{{ playbook_dir }}"
    dest: /home/{{ ssh_user }}
    directory_mode: 0755
    mode: 0755
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
